import { mkdir, readFile, writeFile } from "node:fs/promises";
import { spawn, type ChildProcess } from "node:child_process";
import { constants } from "node:fs";
import { access } from "node:fs/promises";
import { homedir } from "node:os";
import { basename, delimiter, join, resolve } from "node:path";
import {
  cancel,
  confirm,
  intro,
  isCancel,
  note,
  outro,
  spinner,
} from "@clack/prompts";

import { runHookCommand } from "./hook.js";
import { detectAuraKeeperHook, inspectProject } from "../lib/project.js";

const DEFAULT_PORT = 3000;
const LOCAL_ADMIN_TOKEN = "aurakeeper-local-admin";
const LOCAL_DIRECTORY = ".aurakeeper";
const LOCAL_STATE_FILE = "local.json";
const LOCAL_ENV_FILE = "local.env";

type LocalCommandArgs = {
  port: number;
  devCommand: string[];
};

type LocalState = {
  projectId: string;
  apiToken: string;
  endpoint: string;
  port: number;
};

function usage(): string {
  return [
    "Usage: aurakeeper local [--port <number>] [-- <dev command>...]",
    "",
    "Options:",
    "  --port <number>   Port for the local AuraKeeper backend",
    "",
    "Examples:",
    "  aurakeeper local",
    "  aurakeeper local -- npm run dev",
  ].join("\n");
}

function assertNotCancelled<T>(value: T | symbol): T {
  if (isCancel(value)) {
    cancel("AuraKeeper local cancelled.");
    process.exit(0);
  }

  return value as T;
}

function parseLocalArgs(argv: string[]): LocalCommandArgs {
  const devSeparator = argv.indexOf("--");
  const commandArgs =
    devSeparator === -1 ? argv : argv.slice(0, devSeparator);
  const devCommand = devSeparator === -1 ? [] : argv.slice(devSeparator + 1);
  let port = DEFAULT_PORT;

  for (let index = 0; index < commandArgs.length; index += 1) {
    const arg = commandArgs[index];

    if (arg === "--help" || arg === "-h") {
      console.log(usage());
      process.exit(0);
    }

    if (arg === "--port") {
      const value = commandArgs[index + 1];
      const parsed = Number.parseInt(value ?? "", 10);

      if (!value || Number.isNaN(parsed) || parsed <= 0) {
        throw new Error("Expected --port to be a positive integer.");
      }

      port = parsed;
      index += 1;
      continue;
    }

    if (arg.startsWith("--port=")) {
      const parsed = Number.parseInt(arg.slice("--port=".length), 10);

      if (Number.isNaN(parsed) || parsed <= 0) {
        throw new Error("Expected --port to be a positive integer.");
      }

      port = parsed;
      continue;
    }

    throw new Error(`Unknown option for local: ${arg}`);
  }

  return {
    port,
    devCommand,
  };
}

function createManagedEnvFileContent(variables: Record<string, string>): string {
  const lines = [
    "# AuraKeeper local environment",
    "# Generated by `aurakeeper local`.",
    "",
  ];

  for (const [key, value] of Object.entries(variables)) {
    lines.push(`${key}=${value}`);
  }

  lines.push("");
  return lines.join("\n");
}

async function readLocalState(statePath: string): Promise<LocalState | null> {
  try {
    const parsed = JSON.parse(await readFile(statePath, "utf8")) as Partial<LocalState>;

    if (
      typeof parsed.projectId !== "string" ||
      typeof parsed.apiToken !== "string" ||
      typeof parsed.endpoint !== "string" ||
      typeof parsed.port !== "number"
    ) {
      return null;
    }

    return {
      projectId: parsed.projectId,
      apiToken: parsed.apiToken,
      endpoint: parsed.endpoint,
      port: parsed.port,
    };
  } catch {
    return null;
  }
}

async function writeLocalState(statePath: string, state: LocalState): Promise<void> {
  await writeFile(statePath, `${JSON.stringify(state, null, 2)}\n`, "utf8");
}

async function ensureBackendDirectoryExists(path: string): Promise<void> {
  try {
    await access(path, constants.F_OK);
  } catch {
    throw new Error(
      `AuraKeeper backend sources were not found at ${path}. Set up this command from the monorepo checkout before using \`aurakeeper local\`.`
    );
  }
}

async function fileExists(path: string): Promise<boolean> {
  try {
    await access(path, constants.X_OK);
    return true;
  } catch {
    return false;
  }
}

async function resolveExecutable(
  executableName: string,
  overrides: Array<string | undefined> = []
): Promise<string | null> {
  for (const override of overrides) {
    if (!override) {
      continue;
    }

    if (await fileExists(override)) {
      return override;
    }
  }

  const pathEntries = (process.env.PATH ?? "")
    .split(delimiter)
    .map((entry) => entry.trim())
    .filter((entry) => entry.length > 0);

  const candidateNames =
    process.platform === "win32"
      ? [executableName, `${executableName}.exe`, `${executableName}.cmd`]
      : [executableName];

  for (const directory of pathEntries) {
    for (const candidateName of candidateNames) {
      const candidatePath = join(directory, candidateName);

      if (await fileExists(candidatePath)) {
        return candidatePath;
      }
    }
  }

  return null;
}

async function resolveBunPath(): Promise<string> {
  const homeBunPath =
    process.platform === "win32"
      ? join(homedir(), ".bun", "bin", "bun.exe")
      : join(homedir(), ".bun", "bin", "bun");

  const bunPath = await resolveExecutable("bun", [
    process.env.AURAKEEPER_BUN_PATH,
    process.env.BUN_PATH,
    homeBunPath,
  ]);

  if (!bunPath) {
    throw new Error(
      [
        "AuraKeeper local requires the Bun runtime to start the local backend.",
        "Install Bun or set `AURAKEEPER_BUN_PATH` to the Bun executable before running `aurakeeper local`.",
      ].join(" ")
    );
  }

  return bunPath;
}

async function waitForHealth(endpointBase: string, timeoutMs = 20_000): Promise<void> {
  const startedAt = Date.now();

  while (Date.now() - startedAt < timeoutMs) {
    try {
      const response = await fetch(`${endpointBase}/health`);

      if (response.ok) {
        return;
      }
    } catch {
      // Ignore and retry until timeout.
    }

    await new Promise((resolvePromise) => setTimeout(resolvePromise, 300));
  }

  throw new Error(`Timed out waiting for the local backend at ${endpointBase}.`);
}

function formatCommand(command: string[]): string {
  return command.map((part) => (/\s/.test(part) ? JSON.stringify(part) : part)).join(" ");
}

function spawnProcess(input: {
  command: string;
  args: string[];
  cwd: string;
  env: NodeJS.ProcessEnv;
}): ChildProcess {
  return spawn(input.command, input.args, {
    cwd: input.cwd,
    env: input.env,
    stdio: "inherit",
  });
}

async function createOrUpdateLocalProject(input: {
  baseUrl: string;
  adminToken: string;
  projectName: string;
  checkoutPath: string;
  previousState: LocalState | null;
}): Promise<LocalState> {
  const body = {
    name: input.projectName,
    repair: {
      checkoutPath: input.checkoutPath,
      backend: "local",
      environment: "local",
      trustLevel: "trusted",
      autoTrigger: true,
    },
  };

  if (input.previousState) {
    const updateResponse = await fetch(
      `${input.baseUrl}/v1/projects/${input.previousState.projectId}`,
      {
        method: "PATCH",
        headers: {
          "Content-Type": "application/json",
          "X-Admin-Token": input.adminToken,
        },
        body: JSON.stringify(body),
      }
    );

    if (updateResponse.ok) {
      return {
        projectId: input.previousState.projectId,
        apiToken: input.previousState.apiToken,
        endpoint: `${input.baseUrl}/v1/logs/errors`,
        port: new URL(input.baseUrl).port
          ? Number.parseInt(new URL(input.baseUrl).port, 10)
          : DEFAULT_PORT,
      };
    }
  }

  const createResponse = await fetch(`${input.baseUrl}/v1/projects`, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      "X-Admin-Token": input.adminToken,
    },
    body: JSON.stringify(body),
  });

  if (!createResponse.ok) {
    throw new Error(
      `Failed to provision a local AuraKeeper project (${createResponse.status} ${createResponse.statusText}).`
    );
  }

  const payload = (await createResponse.json()) as {
    id: string;
    token: string;
  };

  return {
    projectId: payload.id,
    apiToken: payload.token,
    endpoint: `${input.baseUrl}/v1/logs/errors`,
    port: new URL(input.baseUrl).port
      ? Number.parseInt(new URL(input.baseUrl).port, 10)
      : DEFAULT_PORT,
  };
}

export async function runLocalCommand(): Promise<void> {
  const args = parseLocalArgs(process.argv.slice(3));
  const cwd = process.cwd();
  const inspection = await inspectProject(cwd);

  intro("AuraKeeper local");

  const hookDetection = await detectAuraKeeperHook(cwd);

  if (!hookDetection.installed) {
    const installHook = assertNotCancelled(
      await confirm({
        message:
          "No AuraKeeper hook was detected in this project. Install it now?",
        initialValue: true,
      })
    );

    if (!installHook) {
      cancel("AuraKeeper local requires an AuraKeeper hook in the target project.");
      process.exit(1);
    }

    await runHookCommand({
      providerOverride: "aurakeeper",
      introText: "AuraKeeper hook",
      outroText: "AuraKeeper hook installed.",
    });
  } else if (hookDetection.evidence.length > 0) {
    note(hookDetection.evidence.map((entry) => `- ${entry}`).join("\n"), "Hook detected");
  }

  const confirmedHook = await detectAuraKeeperHook(cwd);

  if (!confirmedHook.installed) {
    throw new Error(
      "AuraKeeper local could not verify that the hook is installed after setup."
    );
  }

  const backendDir = resolve(import.meta.dirname, "../../../backend");
  await ensureBackendDirectoryExists(backendDir);
  const bunPath = await resolveBunPath();

  const localDir = join(cwd, LOCAL_DIRECTORY);
  const statePath = join(localDir, LOCAL_STATE_FILE);
  const envPath = join(localDir, LOCAL_ENV_FILE);

  await mkdir(localDir, { recursive: true });

  const previousState = await readLocalState(statePath);
  const baseUrl = `http://127.0.0.1:${args.port}`;

  const backendStartup = spinner();
  backendStartup.start(`Starting local AuraKeeper backend on port ${args.port}`);

  const backendProcess = spawnProcess({
    command: bunPath,
    args: ["run", "src/index.ts"],
    cwd: backendDir,
    env: {
      ...process.env,
      ADMIN_TOKEN: LOCAL_ADMIN_TOKEN,
      PORT: String(args.port),
      DATABASE_PATH: join(localDir, "aurakeeper.sqlite"),
      ARTIFACTS_PATH: join(localDir, "artifacts"),
      CORS_ALLOWED_ORIGINS: "*",
    },
  });

  const backendExitPromise = new Promise<number | null>((resolvePromise) => {
    backendProcess.once("exit", (code) => {
      resolvePromise(code);
    });
  });
  const backendErrorPromise = new Promise<never>((_, reject) => {
    backendProcess.once("error", reject);
  });

  try {
    await Promise.race([
      waitForHealth(baseUrl),
      backendErrorPromise,
      backendExitPromise.then((code) => {
        throw new Error(
          `AuraKeeper backend exited before becoming ready${code === null ? "." : ` (code ${code}).`}`
        );
      }),
    ]);
  } catch (error) {
    backendProcess.kill("SIGTERM");
    backendStartup.stop("Failed to start local AuraKeeper backend");
    throw error;
  }

  backendStartup.stop(`Local AuraKeeper backend is ready on ${baseUrl}`);

  let projectState: LocalState;

  try {
    projectState = await createOrUpdateLocalProject({
      baseUrl,
      adminToken: LOCAL_ADMIN_TOKEN,
      projectName: inspection.projectName || basename(cwd),
      checkoutPath: cwd,
      previousState,
    });

    await writeLocalState(statePath, projectState);

    await writeFile(
      envPath,
      createManagedEnvFileContent({
        AURAKEEPER_ENDPOINT: projectState.endpoint,
        AURAKEEPER_API_TOKEN: projectState.apiToken,
      }),
      "utf8"
    );
  } catch (error) {
    backendProcess.kill("SIGTERM");
    await backendExitPromise;
    throw error;
  }

  note(
    [
      `Endpoint: ${projectState.endpoint}`,
      `API token: ${projectState.apiToken}`,
      `Saved env file: ${envPath}`,
      args.devCommand.length > 0
        ? `Dev command: ${formatCommand(args.devCommand)}`
        : "Run your app with the env values above, or use `aurakeeper local -- <command>`.",
    ].join("\n"),
    "Local setup"
  );

  let shuttingDown = false;
  let devProcess: ChildProcess | null = null;

  const shutdown = (signal: NodeJS.Signals) => {
    if (shuttingDown) {
      return;
    }

    shuttingDown = true;

    if (devProcess && !devProcess.killed) {
      devProcess.kill(signal);
    }

    if (!backendProcess.killed) {
      backendProcess.kill(signal);
    }
  };

  process.once("SIGINT", () => shutdown("SIGINT"));
  process.once("SIGTERM", () => shutdown("SIGTERM"));

  if (args.devCommand.length > 0) {
    const [command, ...commandArgs] = args.devCommand;

    devProcess = spawnProcess({
      command,
      args: commandArgs,
      cwd,
      env: {
        ...process.env,
        AURAKEEPER_ENDPOINT: projectState.endpoint,
        AURAKEEPER_API_TOKEN: projectState.apiToken,
      },
    });

    const devExitCode = await new Promise<number | null>((resolvePromise, reject) => {
      devProcess!.once("error", (error) => {
        shutdown("SIGTERM");
        reject(error);
      });
      devProcess!.once("exit", (code) => {
        resolvePromise(code);
      });
    });

    shutdown("SIGTERM");
    await backendExitPromise;
    outro("AuraKeeper local stopped.");
    process.exit(devExitCode ?? 0);
  }

  outro("AuraKeeper local is running. Press Ctrl+C to stop.");
  await backendExitPromise;
}
